service: cde-aws-java
provider:
  name: aws
  role: ${self:custom.role.${opt:stage}}
  runtime: java8
  timeout: 60
  versionFunctions: false
package:
  artifact: build/distributions/cde-fn-sdcValidate.zip
functions:
  cde-fn-sdcValidate:
    handler: gov.nih.nlm.cde.sdcValidate.Handler
    name: cde-fn-sdcValidate-${opt:stage, 'dev'}
    timeout: 300
  cde-zip-export:
    handler: gov.nih.nlm.cde.zipExport.Handler
    name: cde-zip-export-${opt:stage, 'dev'}
    timeout: 300
custom:
  role:
    green: arn:aws:iam::070163433501:role/nlm_basic_lambda_role
    blue: arn:aws:iam::070163433501:role/nlm_basic_lambda_role
    qa-green: arn:aws:iam::491634416615:role/nlm_basic_lambda_role
    qa-blue: arn:aws:iam::491634416615:role/nlm_basic_lambda_role
