exports.map = {
    "umol/L": "",
    "copies": "",
    "g": "",
    "Ratio": "",
    "mmol/L": "",
    "umol/L;mcmol/L": "",
    "mIU/L": "",
    "ug/dL": "",
    "ratio": "",
    "ng/mL": "",
    "%": "",
    "umol/L/h": "",
    "U/g Hb": "",
    "umol/h/L": "",
    "mg/dL": "",
    "ug/L": "",
    "ng/dL": "",
    "min": "",
    "molar ratio": "",
    "wk": "",
    "clock time": "",
    "/min": "",
    "h": "",
    "ng/ng": "",
    "nmoL/mL/min": "",
    "µmol/L": ""
};