exports.map = {
    "umol/L": "Number",
    "copies": "Number",
    "g": "Number",
    "Ratio": "Text",
    "mmol/L": "Number",
    "umol/L;mcmol/L": "Number",
    "mIU/L": "Number",
    "ug/dL": "Number",
    "ratio": "Text",
    "ng/mL": "Number",
    "%": "Number",
    "umol/L/h": "Number",
    "U/g Hb": "Number",
    "umol/h/L": "Number",
    "mg/dL": "Number",
    "ug/L": "Number",
    "ng/dL": "Number",
    "min": "Number",
    "molar ratio": "Text",
    "wk": "Number",
    "clock time": "Number",
    "/min": "Number",
    "h": "Number",
    "ng/ng": "Number",
    "nmoL/mL/min": "Number",
    "µmol/L": "Number"
};