package gov.nih.nlm.system;

import java.util.HashMap;
import java.util.Map;

public class EltIdMaps {

    public static Map<String, String> eltMap = new HashMap<>();

    static {
        eltMap.put("Additional Dimension", "XyEbt94V_");
        eltMap.put("Adrenal Gland Received Other Specify", "Q1AVwqNVb");
        eltMap.put("Alcohol use started age value", "FtNNFMKHCM4");
        eltMap.put("Atherosclerosis Risk in Communities transient ischemic attack/stroke form (ARIC TIA) - speech loss slurred symptom indicator", "0gqqG2jShnS");
        eltMap.put("Apgar Score Created By java.lang.Long", "GvOOag_P4Zg");
        eltMap.put("Biomarker Outcome Characteristics java.lang.String", "_dPmPekTRsb");
        eltMap.put("Brief Pain Inventory (BPI) - pain general activity interference scale", "hPzRsUF_xX5");
        eltMap.put("Classification Scheme Item Relationship Database Identifier java.lang.String", "sf_RFs39Phb");
        eltMap.put("ConceptCDE", "mkBls_Z0M");
        eltMap.put("Common Toxicity Criteria Adverse Event Colitis Grade", "exWjxFqAU7r");
        eltMap.put("Common Toxicity Criteria Adverse Event Hypophosphatemia Grade", "75Y5R3FH5ar");
        eltMap.put("cde for test cde reorder detail tabs", "7yl__aTQOe");
        eltMap.put("Cde Delete Test", "7yl_YaTQOe");
        eltMap.put("Data source", "_URwV8TsYjS");
        eltMap.put("Definition Type Definition Type String", "OoKQxxjOGzT");
        eltMap.put("Draft Cde Test", "QyT6ElNKLl");
        eltMap.put("ExportLatest", "XkZpBf60z");
        eltMap.put("FAD Total score value", "fp_oYN6A_SJ");
        eltMap.put("Family Assessment Device (FAD) - Discuss problem indicator", "mrKyN_kpt86");
        eltMap.put("Feature Modified By java.lang.String", "GKrk4H_tWNZ");
        eltMap.put("Form Element End Date", "UwnYawNOWYw");
        eltMap.put("Gastrointestinal therapy water flush status", "HyQz9G0oYaE");
        eltMap.put("Genotype Therapy Basis Mutation", "PwdyV7rn1Pp");
        eltMap.put("Hospital Confidential Institution Referred From Facility Number Code", "Hemf6zdy6o4");
        eltMap.put("History data reliability type", "K8v6jJWkmmC");
        eltMap.put("Identifier Primary Flag java.lang.Boolean", "JwrG4XOq2jZ");
        eltMap.put("Illicit/non-prescription drug use indicator", "6jfk971GhEu");
        eltMap.put("Immunology Gonorrhea Assay Laboratory Finding Result", "hYUh3yYR0mH");
        eltMap.put("In the past 7 days, when I was in pain I protected the part of my body that hurt", "Xyl_qyuhJ7e");
        eltMap.put("In the past 7 days, when I was in pain I moved slower", "QJmc1OnyQe");
        eltMap.put("In the past 7 days, when I was in pain I asked for medicine", "myg51_nyXg");
        eltMap.put("Investigator Identifier java.lang.Integer", "wT3DsGm_bea");
        eltMap.put("Left Lymph Node Positive Total Count", "xNugcDxoqKW");
        eltMap.put("Lesion Nontarget Location Type", "t1SaH4wGZkJ");
        eltMap.put("Lower limb tone findings result", "Rv51YEvZyMJ");
        eltMap.put("Little interest or pleasure in doing things in last 2 weeks [Reported.PHQ]", "QkWPURx5Fz");
        eltMap.put("Malignant Neoplasm Metastatic Involvement Anatomic", "cyPNj_m8r1V");
        eltMap.put("Malignant Neoplasm Surgical Margin Distance Value", "_d7K6T3_Z4Q");
        eltMap.put("McGill Quality of Life Questionnaire (MQOL) - troublesome physical symptom problem score", "QXpcS9boYtk");
        eltMap.put("Medication affecting cardiovascular function type exam day indicator", "xug6J6R8fkf");
        eltMap.put("Mediastinal Lymph Node Physical Examination Specify", "64YoxVrtASF");
        eltMap.put("Metastatic Disease or Disorder Magnetic Resonance Imaging Cerebrospinal Fluid Diagnosis Ind-2", "y2Z_uqAo_3j");
        eltMap.put("Neoadjuvant Therapy", "7yN4tn_EW");
        eltMap.put("Number of Pregnancies", "oW10_UFbA2c");
        eltMap.put("Oosterhuis score", "WEoSbBfqEDx");
        eltMap.put("Other Group Patient Identifier Number", "hvsUN03ToUz");
        eltMap.put("Patient Eligibility Ind-2", "obP4FhjUQTY");
        eltMap.put("Patient Gender Code", "bzGjaFPtQCs");
        eltMap.put("Patient Newly Diagnosed INSS Stage 4 Neuroblastoma With Unfavorable Feature Eligibility Criteria Yes No Indicator", "FdhGNj4gd6e");
        eltMap.put("Patient Photograph Malignant Neoplasm Assessment Date", "UDUXvtj1RM2");
        eltMap.put("Patient Visual Change Chief Complaint Indicator", "q3bWgQN1wCq");
        eltMap.put("Pattern Transfer Retrieval Storage Data Research Activity Consortium or Network Or Professional Organization or Group Funding Mechanism FundingMechanismCode", "qPsdBFBSTRc");
        eltMap.put("Person Birth Date", "2yWPshAKKN7");
        eltMap.put("Person Elevated Urine Protein Measurement Clinical Trial Eligibility Criteria Yes No Indicator", "HrVtaZ7EtxQ");
        eltMap.put("Person Mother Onset Menopause Age Value", "qKGWuJZ1zxz");
        eltMap.put("Principal Investigator State java.lang.String", "71Tn0ywTKNO");
        eltMap.put("Psychiatric history clinical depression past year indicator", "ryD6agS7yuQ");
        eltMap.put("Pulmonary function lung function measurement", "CC09PXVh8dF");
        eltMap.put("PvValidatorCde", "7Jn4ByTd_");
        eltMap.put("Revised Childrens Anxiety and Depression Scale (RCADS) - School attendance trouble nervous afraid scale", "7k_flGOZ_3de");
        eltMap.put("Reorder reference document cde", "QJE9qwgEP");
        eltMap.put("Reorder properties cde", "mkgGjDg4D");
        eltMap.put("Reorder concept cde", "71EPiweND");
        eltMap.put("Reorder permissible values cde", "QkOasvgNP");
        eltMap.put("Reorder designations cde", "71Cz2vxNv");
        eltMap.put("Sarcoma Dominant Histology Type", "KHj2gnZqxZW");
        eltMap.put("Scale for Outcomes in PD Autonomic (SCOPA-AUT) - urinate night indicator", "NuQwuCAZrz5");
        eltMap.put("SDC Adrenal", "XySUBn_NZ");
        eltMap.put("Service Item Display Name java.lang.String", "_Qg5FbwRP98");
        eltMap.put("Specimen Block Received Count", "fPFAp0Onkcx");
        eltMap.put("Specimen Inflammation Change Type", "vdw_hgaMyxc");
        eltMap.put("Specimen Array", "vdw_hgaMyxc");
        eltMap.put("Sensory system abnormality stocking glove present text", "gPY57SQ7_ZF");
        eltMap.put("Spectroscopy geometry location not applicable indicator", "soCkdnmqN8H");
        eltMap.put("Surgical Procedure Hand Laparoscopic Port Anatomic Site", "ymKeneM5_DB");
        eltMap.put("Target Lesion Sum Short Longest Dimension Measurement", "_6G_NPfQK0G");
        eltMap.put("Tissue Donor Genetic Testing Other Disease or Disorder Specify", "nsMXB5NdFBA");
        eltMap.put("Temperature mean daily measurement", "rErbwwAasvz");
        eltMap.put("Temperature peak measurement value", "zXfSfKPe5Uv");
        eltMap.put("Temperature measurement", "2V9Th1t2guY");
        eltMap.put("Temperature maximum daily measurement", "hO8j7EqG61K");
        eltMap.put("Treatment Text Other Text", "3XoxhY_Xv8x");
        eltMap.put("Trouble falling or staying asleep, or sleeping too much in last 2 weeks [Reported.PHQ]", "m1xj2YMI1X");
        eltMap.put("UnclassifiedCDE", "mkH_UGXEw");
        eltMap.put("Urinary tract surgical procedure indicator", "9h_xBFxdO4e");
        eltMap.put("Urinary tract drug type last year type", "c56fasYoV1T");
        eltMap.put("Vision (aura) typical symptom type", "rRqc8KG1RNO");

        // Forms
        eltMap.put("Activities of Daily Living and Gait", "QyVcb1Srtg");
        eltMap.put("Adverse Event Tracking Log ", "m1_5_1HBYl");
        eltMap.put("AED Resistance Log", "7yxcZJrrte");
        eltMap.put("Acute Admission/Discharge", "XkS5WJHrtg");
        eltMap.put("ALS Depression Inventory (ADI-12)", "QJW5Z1BrYl");
        eltMap.put("Antithrombotics and Risk Factor Controlling Medications", "XJfnZyHrYg");
        eltMap.put("Behavioral History", "mJCZyrSte");
        eltMap.put("Body Mass Index", "XyZ43DXGU");
        eltMap.put("Brain Motor Control Assessment", "XJJzyBSKe");
        eltMap.put("DNA Elements - Information from the Laboratory", "X1x4z1BrYx");
        eltMap.put("Copy Section Form Test", "Xy7W4MKNV");
        eltMap.put("DNA Elements - Participant/Subject Information", "m1fVM1SSFx");
        eltMap.put("DateTypeTest", "7y_PFN4Zr");
        eltMap.put("Double Classif Form", "QJgAXYdXv");
        eltMap.put("Draft Form Test", "QyT6ElYKLl");
        eltMap.put("Drag Question Test", "7kL4X8sMU");
        eltMap.put("Dynamic Code List Form", "XkY_oO2zv");
        eltMap.put("Empty Logic", "7kAx6i5af");
        eltMap.put("Empty Section Form", "Q1CSvNQhW");
        eltMap.put("Frontal Behavioral Inventory (FBI)", "XJbbmJSrFe");
        eltMap.put("Functional Imaging", "my7XySBtg");
        eltMap.put("Form Cde Update Test", "X1ghWjntf");
        eltMap.put("Form Delete Test", "QyT6ElOKLl");
        eltMap.put("Form Form Update Test", "7kAWJ9gHB");
        eltMap.put("Form History Test", "QkGEqKVNZ");
        eltMap.put("Form History Compare Test", "XJQfsXNjz");
        eltMap.put("formAddCdeTest", "7kkK62xR4");
        eltMap.put("formAddSuggestedCdeTest", "7kkY62xR4");
        eltMap.put("Answer List Test", "XyWvhfX4W");
        eltMap.put("Form Table Test", "713d9u1vX");
        eltMap.put("Geo Location Test", "QkdP0NeH8");
        eltMap.put("History Data Source and Reliability", "Q1rvXyHBFx");
        eltMap.put("Imaging OCT Analysis - Spectralis Report Analysis", "XJrcQ1HSFx");
        eltMap.put("Loinc Widget Test Form", "Q1ncc4Rg_");
        eltMap.put("McGill Quality of Life Questionnaire (MQOL)", "Xk44kSSYe");


        // Display Profile Tests
        eltMap.put("Matrix Display Profile Test", "QktaN3OFL1");
        eltMap.put("Answer Value Display Profile Test", "QktaN3OFL2");
        eltMap.put("Metadata Device Display Profile Test", "QktaN3OFL3");
        eltMap.put("Multiple Select Display Profile Test", "QktaN3OFL4");

        eltMap.put("Mean Value Test", "X17IaQ_NQ");
        eltMap.put("Measures of Gas Exchange", "Q1eNEJrHtx");
        eltMap.put("Motor Evoked Potentials", "mkWON1SrFe");
        eltMap.put("MultiSelect Logic", "mJSv499pz");
        eltMap.put("Multi SubQuestion", "mk4r3nH77");
        eltMap.put("Neurological Assessment: TBI Symptoms and Signs", "mkqnEJHrtl");
        eltMap.put("Non Editable Questions", "m16LQuUCG");
        eltMap.put("Non-Pathology Findings", "mJQiShWEW");
        eltMap.put("Not Equals Test", "QJBWLKc47");
        eltMap.put("PhenX Form RedCAP Export", "XJ_vOJ9iZ");
        eltMap.put("Patient Health Questionnaire-2 (PHQ-2)", "XJzVz1TZDe");
        eltMap.put("Patient Health Questionnaire-2 (PHQ-2) More Questions", "XJzVXFTZDR");
        eltMap.put("Patient Health Questionnaire 2 item (PHQ-2) [Reported]", "XkZqYRlqKf");
        eltMap.put("PHQ-9 quick depression assessment panel [Reported.PHQ]", "mJsGoMU1m");
        eltMap.put("Patient Health Questionnaire - 9 (PHQ-9) Depression Scale", "mJP_B1HrFg");
        eltMap.put("PROMIS Bank v1.0 - Anxiety", "mksbrh_YIx");
        eltMap.put("PROMIS Bank v1.2 - Physical Function", "Xko4nuKLg");
        eltMap.put("PROMIS Parent Proxy SF v1.0 - Peer Relations 7a", "Q1N5NhuY8g");
        eltMap.put("PROMIS SF v1.0-Fatigue 8a", "QyTY42OFIg");
        eltMap.put("PROMIS SF v2.0 - Instrumental Support 8a", "7JrNn_FIx");
        eltMap.put("PROMIS SF v1.0 - Applied Cog Abilities 4a", "Q1Ogr2OtIe");
        eltMap.put("PROMIS SF v1.0 - Pain Behavior 7a", "QkggxHhuF8x");
        eltMap.put("PROMIS SF v1.0-Sleep Disturbance 4a", "Q1JxnV2OYIx");
        eltMap.put("PROMIS SF v1.0-Sleep Disturbance 6a", "QJbbHnOFUl");
        eltMap.put("PROMIS SF v1.1 - Anger 5a", "mk8PNndtLg");
        eltMap.put("PROMIS SF v2.0 - Instrumental Support 4a", "mkG_EhdYIe");
        eltMap.put("PROMIS SF v2.0 - Companionship 6a", "m1BxH3_tIe");
        eltMap.put("PTSD Checklist - Civilian (PCL-C)", "7JZgS1BrKx");
        eltMap.put("Question Repeat", "XkCtybYXB");
        eltMap.put("Recursive Form", "mkMUtAXlI");
        eltMap.put("Remove SkipLogic Form", "X1s87bif7");
        eltMap.put("Reorder reference document form", "7yxjmyAQP");
        eltMap.put("Reorder definition form", "myYlSJAQD");
        eltMap.put("Section in Section Form", "Q11QuVmN_");
        eltMap.put("Section Inside Section Form", "71AKDVQhW");
        eltMap.put("Section Test Form", "XJFylVmN_");
        eltMap.put("Section Test Form2", "mycc3Hcf8");
        eltMap.put("Section Test Form3", "mkmn3Bcz8");
        eltMap.put("Section Test Form4", "71WanHqGU");
        eltMap.put("Socioeconomic Status", "XyMzLyBHYl");
        eltMap.put("Skip Logic Number Test Form", "7ycTkMnAI");
        eltMap.put("Skip Logic Text Test Form", "mJjMCG30U");
        eltMap.put("Skip Logic Date Test Form", "71t5G120U");
        eltMap.put("Skip Logic Value List Test Form", "mJVPzQ2C8");
        eltMap.put("Skip Logic No Label Form", "myMbx38V7");
        eltMap.put("Stroke Symptoms/Comorbid Events", "7kqGIJBBKg");
        eltMap.put("Stroke Types and Subtypes", "QkX81HrFx");
        eltMap.put("Study Discontinuation/Completion", "myWQUJrHFg");
        eltMap.put("Study Drug Compliance", "71zmIkrBtl");
        eltMap.put("Surgical and Procedural Interventions", "myoQ8JBHFe");
        eltMap.put("TextAreaForm", "QJFFX4ERL");
        eltMap.put("Traumatic Brain Injury - Adverse Events", "sdsflijkfsd");
        eltMap.put("Type, Place, Cause and Mechanism of Injury", "XyqIIyrBtx");
        eltMap.put("Two Dimensional Speckle Tracking Echocardiography Imaging", "7kKLUkHBtl");
        eltMap.put("UnclassifiedForm", "71m0HfXEv");
        eltMap.put("Written Verbal Fluency Test", "QklqIkSrKx");
        eltMap.put("Vessel Imaging Angiography", "XJDPIySHtx");
        eltMap.put("Vital Signs and Tests", "XyWYLJSBKx");

        //Boards
        eltMap.put("Blood Board", "5711497e28329938330f5c4c");
        eltMap.put("Board Export Test", "56bb7e300210aac4271b4335");
        eltMap.put("Bipolar Disorder", "55f198c8541fd83c2166cbe2");
        eltMap.put("Chronic Lower-Back Pain", "55f197d6541fd83c2166cbc9");
        eltMap.put("Classify Board", "56e6d3c4439b3598287b5769");
        eltMap.put("Cerebral Palsy", "55f1974a541fd83c2166cbbe");
        eltMap.put("Double Pin Board", "5750470189949d54384ee625");
        eltMap.put("Form Board", "5751ee614184ddb440886745");
        eltMap.put("Gliobastroma Multiform", "55f19768541fd83c2166cbc4");
        eltMap.put("Hypertension", "55f19808541fd83c2166cbcf");
        eltMap.put("Num Of Questions Board", "585c2ced523c738c23ed8e0b");
        eltMap.put("Pin All CDEs From Form", "574ef30bb8d73fd82a7ac6b2");
        eltMap.put("Pin All Less Than 20 Test Board", "5750432731f3ccb83b82896c");
        eltMap.put("Pin All More Than 20 Test Board", "5750434631f3ccb83b82896f");
        eltMap.put("Plantar Fibromatosis", "55f197e0541fd83c2166cbcc");
        eltMap.put("Public Board", "5750474d89949d54384ee640");
        eltMap.put("Public Smoking Board", "575045748ad83ed43a3b7ebd");
        eltMap.put("Reg Status Lift", "mJmg93zRW");
        eltMap.put("Smoking Board", "5711498c28329938330f5c4f");
        eltMap.put("Schizophrenia", "55f198bf541fd83c2166cbdf");
        eltMap.put("Stomach Cancer", "55f19755541fd83c2166cbc1");
        eltMap.put("Test Pinning Board", "5755db5a4dace9c03f784a9f");
        eltMap.put("Unpin Board", "57114b5328329938330f5c7f");
        eltMap.put("Depression", "55f198ac541fd83c2166cbdc");

        eltMap.put("Gender Self-Identified", "7yXnzmPgZ");
    }

}
