export const map = {
    '%': 'Number',
    '/min': 'Number',
    'clock time': 'Number',
    copies: 'Number',
    g: 'Number',
    h: 'Number',
    lb: 'Number',
    'm[IU]/L': 'Number',
    'mcg/dL': 'Number',
    'mcmol/L': 'Number',
    'mg/dL': 'Number',
    min: 'Number',
    'mIU/L': 'Number',
    'mmol/L': 'Number',
    'molar ratio': 'Text',
    'ng/dL': 'Number',
    'ng/mL': 'Number',
    'ng/ng': 'Number',
    'nmol/h/mL': 'Number',
    'nmoL/mL/min': 'Number',
    Ratio: 'Text',
    ratio: 'Text',
    'U/g Hb': 'Number',
    'ug/dL': 'Number',
    'ug/L': 'Number',
    'umol/h/L': 'Number',
    'umol/L': 'Number',
    'umol/L/h': 'Number',
    'umol/L;mcmol/L': 'Number',
    wk: 'Number',
    '{clock_time}': 'Number',
    '{copies}': 'Number',
    '{Ratio}': 'Text',
    '{ratio}': 'Text',
    'µmol/L': 'Number',
    '[ft_us]/[ft_us]': 'Number',
    um: 'Number',
    '{log}': 'Number',
    '{logMAR}': 'Number',
    '{cells}': 'Number',
    mm: 'Number',
    'mm[Hg]': 'Number',
    cm: 'Number',
    '[diop]': 'Number',
    deg: 'Number',
    a: 'Number',
    mv: 'Number',
    mV: 'Number',
    ms: 'Number',
    '{mm/dd/yyyy}': 'Date',
    '{score}': 'Number',
    'd/(7.d)': 'Number',
    'min/d': 'Number',
    '{#}/d': 'Number',
    '{#}/wk': 'Number',
    '{#}': 'Number',
    '/wk': 'Number',
    '/a': 'Number',
    '[in_i]': 'Number',
    kg: 'Number',
    'mm Hg': 'Number',
    'INCH(S)': 'Number',
    '{Log_copies}/mL': 'Number',
    '{copies}/mL': 'Number',
    'm[IU]/mL': 'Number',
    '[IU]/mL': 'Number'
};
