export const map = {
    Ratio: 'Text',
    ratio: 'Text',
    'molar ratio': 'Text',
    '{Ratio}': 'Text',
    '{ratio}': 'Text',


    '%': 'Number',
    '/min': 'Number',
    'clock time': 'Number',
    copies: 'Number',
    g: 'Number',
    h: 'Number',
    lb: 'Number',
    'm[IU]/L': 'Number',
    'mcg/dL': 'Number',
    'mcmol/L': 'Number',
    'mg/dL': 'Number',
    min: 'Number',
    'mIU/L': 'Number',
    'mmol/L': 'Number',
    'ng/dL': 'Number',
    'ng/mL': 'Number',
    'ng/ng': 'Number',
    'nmol/h/mL': 'Number',
    'nmoL/mL/min': 'Number',
    'U/g Hb': 'Number',
    'ug/dL': 'Number',
    'ug/L': 'Number',
    'umol/h/L': 'Number',
    'umol/L': 'Number',
    'umol/L/h': 'Number',
    'umol/L;mcmol/L': 'Number',
    wk: 'Number',
    '{clock_time}': 'Number',
    '{copies}': 'Number',
    'µmol/L': 'Number',
    '[ft_us]/[ft_us]': 'Number',
    um: 'Number',
    '{log}': 'Number',
    '{logMAR}': 'Number',
    '{cells}': 'Number',
    mm: 'Number',
    'mm[Hg]': 'Number',
    cm: 'Number',
    '[diop]': 'Number',
    '[lb_av];kg;g': 'Number',
    deg: 'Number',
    a: 'Number',
    mv: 'Number',
    mV: 'Number',
    ms: 'Number',
    '{score}': 'Number',
    'd/(7.d)': 'Number',
    'min/d': 'Number',
    '{#}/d': 'Number',
    '{#}/wk': 'Number',
    '{#}': 'Number',
    '/wk': 'Number',
    '/a': 'Number',
    '[in_i]': 'Number',
    kg: 'Number',
    'mm Hg': 'Number',
    'INCH(S)': 'Number',
    '{Log_copies}/mL': 'Number',
    '{copies}/mL': 'Number',
    'm[IU]/mL': 'Number',
    '[IU]/mL': 'Number',
    '[in_us];cm': 'Number',
    '[lb_av]': 'Number',
    'h/wk': 'Number',
    'h/d': 'Number',
    'mo/a': 'Number',
    '/d': 'Number',
    'd/mo': 'Number',
    '[oz_av]/wk': 'Number',
    s: 'Number',
    L: 'Number',
    'L/s': 'Number',
    mL: 'Number',
    '{#}/(3.mo)': 'Number',
    '{#}/{night}': 'Number',
    '{#}/(12.mo)': 'Number',
    'h/(5.d)': 'Number',
    '%{baseline}': 'Number',
    '/(3.a)': 'Number',
    'h/{night}': 'Number',
    'd/(30.d)': 'Number',
    '{#}/(30.d)': 'Number',
    '{#}/wk;{#}/mo;{#}/a': 'Number',
    'd/(3.mo)': 'Number',
    '{#}/d; {#}/wk; {#}/mo': 'Number',
    '{beats}/min': 'Number',
    '{#}/(2.min)': 'Number',
    'kg/m2': 'Number',
    '{#}/a': 'Number',
    'd/(12.mo)': 'Number',

    'd;wk;mo;a': 'Date',
    '{mm/dd/yyyy}': 'Date',
    '{yyyy}': 'Date',
    mo: 'Date',
    '{mm/yyyy}': 'Date',
    '{hh:min}': 'Date',
    '{date}': 'Date',
};
