export const map = {
    Component: 'objectClass',
    'Fragments for synonyms': 'property',
    Property: 'property',
    Scale: 'property',
    System: 'property',
    Time: 'property',
    'Time Modifier': 'property',
    'Super System': 'property',
    Divisors: 'property',
    Method: 'property',
    Multipart: 'property',
    Challenge: 'property',
    Suffix: 'property',
    Quotients: 'property',
    Class: 'property',
};
