import { capString } from 'shared/system/util';

export const htmlServedUri: string[] = [
    '/',
    '/404',
    '/api',
    '/board/:id',
    '/boardList',
    '/cde/search',
    '/cdeStatusReport',
    '/classificationManagement',
    '/contactUs',
    '/createCde',
    '/createForm',
    '/deView',
    '/form/search',
    '/formEdit',
    '/formView',
    '/help/:title',
    '/home',
    '/login',
    '/myBoards',
    '/orgAccountManagement',
    '/orgAuthority',
    '/orgComments',
    '/profile',
    '/quickBoard',
    '/sdcview',
    '/searchPreferences',
    '/siteAudit',
    '/siteAccountManagement',
    '/whatsNew'
];
