#!/bin/bash
# myapp daemon
# chkconfig: 345 20 80

## Script will expect the following to be set
## MONGO_URI (if not set, will default to mongodb://localhost/nlmcde)
## PORT (or will default to 3000, which is fine)
## VSAC_USERNAME (has to be valid)
## VSAC_PASSWORD (valid password)

## !! TODO
## Find a better place for node

. /etc/rc.d/init.d/functions
 
USER="cdeuser"
 
DAEMON="/usr/nlm/cde/node/current/bin/node"
ROOT_DIR="/usr/nlm/cde/code/nlm-cde"
 
SERVER="$ROOT_DIR/app.js"
LOG_FILE="/var/nlm/logs/app.js.log"

NAME=cdeapp 

LOCK_FILE="/var/run/$NAME.pid"
 
do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                cd $ROOT_DIR
                runuser -l "$USER" --session-command "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
       printf "%-50s" "Stopping $NAME"
            PID=`cat $LOCK_FILE`
            cd $DAEMON_PATH
        if [ -f $LOCK_FILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $LOCK_FILE
        else
            printf "%s\n" "pidfile not found"
        fi
}
 
case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL