#!/bin/bash
# myapp daemon
# chkconfig: 345 20 80

## Script will expect the following to be set
## MONGO_URI (if not set, will default to mongodb://localhost/nlmcde)
## PORT (or will default to 3000, which is fine)
## VSAC_USERNAME (has to be valid)
## VSAC_PASSWORD (valid password)

## !! TODO
## Find a better place for node

. /etc/rc.d/init.d/functions
 
USER="cdeuser"
 
DAEMON="/usr/nlm/cde/node-v0.10.12-linux-x64/bin/node"
ROOT_DIR="/usr/nlm/cde/code/nlm-cde"
 
SERVER="$ROOT_DIR/app.js"
LOG_FILE="/var/nlm.log/app.js.log"

NAME=cdeapp 

LOCK_FILE="/var/run/$NAME.pid"
 
do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                runuser -l "$USER" -c "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}
 
case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL