#!/usr/bin/env bash
$loadday = "2015-09-16"
# This file describes how NINDS cde migration works.

1. cd /usr/nlm/apps/code/cde

2. git checkout origin-peter/CDE-636-load-ninds-forms

3. mongo restore migrationCde into migration database
mongorestore  --host=qvlbmongodb02 -d migration -c dataelements dataelements.bson -u siteRootAdmin -p $db_password -authenticationDatabase admin

3. export NODE_ENV=qa-live

4. run updateCde.js as
node ingester/updateNindsCdes.js

5 verify the report:
report:
9888 elements changed
1241 elements Created
0 elements unchanged

4. remote log into mongodb by history   !998
use nlmcde;
db.dataelements.count({
	"source" : "NINDS",
	archived : false,
	"registrationState.registrationStatus" : "Qualified",
	imported : {
		$lt : new ISODate("2015-09-20")
	}
});

5. remote log into mongodb by history   !998
use nlmcde
db.dataelements.update({
	"source" : "NINDS",
	archived : false,
	"registrationState.registrationStatus" : "Qualified",
	imported : {
		$lt : new ISODate("2015-09-20")
	}
}, {
	$set : {
		"registrationState.registrationStatus" : "Retired"
	}
}, {
	multi : true
});

6. remove suggested question text from properties
use nlmcde
db.dataelements.update(
{source: "NINDS", archived: false}
, {$pull: {properties:
{key: "NINDS Suggested Question"}
}},
{multi: true}
)

result: WriteResult({ "nMatched" : 11215, "nUpserted" : 0, "nModified" : 9722 })